language: python
python:
  - "3.5"
install:
  - pip install -U pip
  - pip install coveralls
script:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - echo -e $RESIN_DEPLOY_KEY > id_rsa
  - chmod 0600 id_rsa
  - ssh-add ./id_rsa
  - cat resinkey >> ~/.ssh/known_hosts
  - git remote add resin $RESIN_REMOTE
  - git push resin master
  - coverage run --source=home setup.py test
after_success:
  - coveralls