language: python
python:
  - "2.7"
install:
  - pip install -U pip
  - pip install codecov
script:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - echo -e $RESIN_DEPLOY_KEY > id_rsa
  - chmod 0600 id_rsa
  - ssh-add ./id_rsa
  - cat resinkey >> ~/.ssh/known_hosts
  - git remote add resin $RESIN_REMOTE
  - git push resin master
after_success:
  - bash <(curl -s https://codecov.io/bash)
