install: true
install:
  - pip install coveralls
script:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - echo -e $RESIN_DEPLOY_KEY > id_rsa
  - chmod 0600 id_rsa
  - ssh-add ./id_rsa
  - cat resinkey >> ~/.ssh/known_hosts
  - git remote add resin $RESIN_REMOTE
  - git push resin master
script:
  coverage run --source=resin_bluemix.py test
after_success:
  coveralls